### ISSUE TITLE
Error in installing ecodist from github using devtools

### ISSUE THREAD

**Issue by kspeeriful** [phiala/ecodist#2]
Hello!

I made the unfortunate mistake of updating my version of R. Ever since the update, I have been unable to install ecodist from github using devtools. I'm trying to use logistic MRM and I don't think the CRAN version has the logistic regression bug fix yet, which is why I'd like to download and compile ecodist from here. Below is the error I am getting:

devtools::install_github("phiala/ecodist")
Downloading GitHub repo phiala/ecodist@master
✔  checking for file ‘/private/var/folders/p0/bxmttvw95r3bl3752w_ggcy00000gp/T/RtmpSlG8eE/remotes25e41a05c30/phiala-ecodist-77ad31a/DESCRIPTION’ ...
─  preparing ‘ecodist’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘ecodist’ ...
   ** libs
   gcc-8 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -mtune=native -g -O2 -Wall -pedantic -Wconversion -c ecodist.c -o ecodist.o
   In file included from ecodist.c:1:
   /Library/Frameworks/R.framework/Resources/include/R.h:55:11: fatal error: stdlib.h: No such file or directory
    # include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
              ^~~~~~~~~~
   compilation terminated.
   make: *** [ecodist.o] Error 1
   ERROR: compilation failed for package ‘ecodist’
─  removing ‘/private/var/folders/p0/bxmttvw95r3bl3752w_ggcy00000gp/T/RtmpZyvR9t/Rinst2ab1ad7e356/ecodist’
         -----------------------------------
   ERROR: package installation failed
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

Here is the sessionInfo(). I have xcode-select installed.
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Thanks for any help or suggestions!
Kelly

**Comment by phiala** [comment]
Kelly, your problem is a Mac configuration error, and can occur for any R package compiled from source if you haven't set up xcode completely. This thread provides some possible solutions: https://github.com/catboost/catboost/issues/137

You are correct that the logistic regression fix hasn't been put on CRAN yet; I will eventually get to that! 

But the fix is in R code only - you could use the precompiled Mac package from CRAN, and just swap in MRM.R if the xcode configuration tips don't solve your problem.

**Comment by kspeeriful** [comment]
Hi Sarah,
Thanks so much for the speedy reply! I was able to install ecodist after installing macOS_SDK_headers_for_macOS_10.14. pkg, following the comments on the thread you linked. 
Thanks again!
Kelly
