### ISSUE TITLE
mgram and size limits in R 

### ISSUE THREAD

**Issue by CRyan1** [phiala/ecodist#4]
Hi Sarah, I've had troubles getting mgram to work in R due to R size limits (my dataset has 97,000 rows which  obviusly grows with the distance matrix function). Have you come across this and if so, can you recommend a way to use mgram with bigger data sets? eg is there a way to break them down without losing the spatial integrity? Or another programme that works better? Thank you! Cate

**Comment by sgoslee** [comment]
That's too large to work with effectively in R, as you've discovered.
My suggestion would be to take a random subsample of your data, analyze that, and repeat a bunch of times, as you might for a permutation test.

Or, reformulate your hypothesis in a way that does not require distance matrices.

**Comment by CRyan1** [comment]
Ok, thank you
    On Friday, June 25, 2021, 09:24:42 AM GMT+12, Sarah Goslee ***@***.***> wrote:  
 
 


That's too large to work with effectively in R, as you've discovered.
My suggestion would be to take a random subsample of your data, analyze that, and repeat a bunch of times, as you might for a permutation test.

Or, reformulate your hypothesis in a way that does not require distance matrices.
